services:
  backend:
    build:
      context: .
      dockerfile: server/dockerfile
    container_name: multiplayer_backend
    ports: 
      - "3000:3000"
    environment:
      DATABASE_CONNECTION_STRING: "mongodb+srv://Admin:12345@heroicadventure.ipsvt.mongodb.net/?retryWrites=true&w=majority&appName=HeroicAdventure"
      PORT: "3000"
    restart: unless-stopped
  
  frontend:
    build:
      context: .
      dockerfile: client/dockerfile
    container_name: multiplayer_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
